asiAlgo_Feature          https://analysissitus.org/refdoc/group___a_s_i___a_f_r.html#gad7c43d5647b6c43cb716c21c97147e2f
PushSubgraph             https://analysissitus.org/refdoc/classasi_algo___a_a_g.html#a97f8eedd15ee9b4e072b87ce949acb1e
PopSubgraph              https://analysissitus.org/refdoc/classasi_algo___a_a_g.html#a83167be261ef2eea0afada57622e4c84
asiAlgo_FeatureAngleType https://analysissitus.org/refdoc/group___a_s_i___a_f_r.html#ga2b059f3fe527493a0e28bf432a302f56
AngleBetweenFaces        https://analysissitus.org/refdoc/classasi_algo___check_dihedral_angle.html#a8b9bfec15b23df26e248484996206761
